### PR TITLE
Add MessagePackWriter

### LINKED ISSUE #30: Refactor MessagePackBinary into stateful reader/writer classes
We should split out `MessagePackBinary` into a `MessagePackReader` and `MessagePackWriter` class which store the `ReadOnlySequence<byte>` or `IBufferWriter<byte>` objects they operate on as fields, simplifying the public API and following precedent from other serializer libraries.

### PR DESCRIPTION
**Pull request by AArnott**
This replaces the `ref byte[]`, offset and bytes written return value, but still uses those values underneath the new `MessagePackWriter` struct.

This is a piece of what used to be in #27 

Closes #30

### CODE REVIEW

**Comment by AArnott** [comment]
@neuecc, this is step 2 of 3.

**Comment by neuecc** [comment]
Okay, wait for a moment. (10h-24h)

**Comment by neuecc** [comment]
@AArnott 
Performance:
Maybe introduce `IBufferWriter<byte>` PR causes significal change so I don't check performance, in this PR.

API:

PrimitiveObjectFormatter uses compress write is bad.
https://github.com/AArnott/MessagePack-CSharp/blob/190955c3441311ce88908b809c40c4f25191d0aa/src/MessagePack/Formatters/PrimitiveObjectFormatter.cs#L86
Because it loses type-information.

```csharp
object x = (int)100;
var bin = serializeByPrimitiveObjectFormatter(x);
object y = deserializeByPrimitiveObjectFormatter(bin); // should be int
```

---

NativeDateTimeFormatter was removed, what is the reason?
It is inside in `OldSpecFormatter.cs` file but it is not related to oldspec(sorry...!)
NativeDateTimeFormatter can keep DateTime.Kind and has better performance(only in .NET).
Actually, I was using this formatter with my product.

---

Still exists in OldSpec property in MessagePackWriter, it is really needed?
And removed OldSpecResolver so use can't use in normal path.
I still think that Primitive Writer does not need to have OldSpec property.
User will set resolver or if write primitive, maybe he knows msgpack spec itself.
I think that it is unnecessary to place a low-frequency branch in Writer.

**Comment by AArnott** [comment]
> PrimitiveObjectFormatter uses compress write is bad
> Because it loses type-information

Good point. I'll fix this and add a test for it.

**Comment by AArnott** [comment]
@neuecc It appears *no one* (test or product) within the repo uses `PrimitiveObjectFormatter`. Is that expected?

**Comment by AArnott** [comment]
> NativeDateTimeFormatter was removed, what is the reason?
It is inside in OldSpecFormatter.cs file but it is not related to oldspec(sorry...!)
NativeDateTimeFormatter can keep DateTime.Kind and has better performance(only in .NET).
Actually, I was using this formatter with my product.

I didn't remove it. I moved it into its own file (DateTimeFormatters.cs) since as you say, it isn't related to old-spec.

**Comment by AArnott** [comment]
> Still exists in OldSpec property in MessagePackWriter, it is really needed?

Yes, I think it's appropriate at this level. First consider that the decision to emit old-spec msgpack would be for compatibility with another (older) library. So the decision needs to be applied to _everything_ written to that recipient. Now consider specifically the case of `Write(DateTime)`. There is no way that should work when in OldSpec mode, since that isn't supported by the old spec. Yet if the writer wasn't aware of the need to be in old spec mode, it would happily write it out, causing a compatibility failure on the remote end. But knowing about old spec mode allows us to throw from that method in the writer, allowing the caller to immediately detect their mistake and make corrections before moving on to integration testing or a customer to report the failure. 

> I think that it is unnecessary to place a low-frequency branch in Writer.

The branching isn't hurting perf at all from what I've been able to measure. And as each branch is in either datetime (which has the above mentioned legit case for the check) or in a bulky function that writes out many bytes, a single condition check isn't likely to be a significant perf hit.

> And removed OldSpecResolver so use can't use in normal path.
User will set resolver or if write primitive, maybe he knows msgpack spec itself.

IMO the resolver system is rather hard to grasp when it has so many responsibilities. Having resolvers for the higher level serialization needs like how to encode a .NET complex object makes perfect sense, and that's where nearly all of your resolvers excel. But having one resolver have a rather unique characteristic of simply modifying the very low level writing of a few primtmiive types doesn't sound like a resolver's responsibility. And if I had a requirement as a user of this library to write in oldspec, I would personally be confused about how to combine OldSpec requirements with the other resolvers that I understand better that I need to use. For example, I am using the StandardResolver, but I need old-spec compatibility. How do I get _both_? But when the two switches (resolver vs. oldspec mode) are different switches, it's trivially easy to control them both independently.

**Comment by AArnott** [comment]
> Maybe introduce IBufferWriter<byte> PR causes significal change so I don't check performance, in this PR.

That's fine. The perf should be comparable to baseline in both this PR and the final one. I took pains to measure it at both places.

**Comment by neuecc** [comment]
In the beginning, User usually does not use primitive Writer/Reader directly.
You have to make sure that the situation you have to use directly does not occur as much as possible.

> For example, I am using the StandardResolver, but I need old-spec compatibility. How do I get both? 

```csharp
// or RegisterSetAsDefault
CompositeResolver.Create(
    OldSpecResolver.Instance,
    StandardResolver.Instance
);
```

What's wrong with this?

**Comment by AArnott** [comment]
> What's wrong with this?

For that code to make sense to me, I have to first know and understand:
1. that StandardResolver exists and is the default
1. That StandardResolver can format primitive types and does so with the newer spec.
1. I have to be aware of the existance of `OldSpecResolver` and that it does part of what I want.
1. I have to know about `CompositeResolver`, and that I can use it to override behavior of one resolver with another.
1. I have to know that "first one wins" is the policy for the CompositeResolver.

That's a lot of stuff to know, when all I want is the default behavior, but with old spec compatibility.

Contrast this with this option:

```cs
var serializer = new MessagePackSerializer { OldSpec = true };
```

This is super-discoverable, and doesn't require that I understand any resolvers at all.

I obviously haven't defined this property on `MessagePackSerializer` yet. I was thinking that OldSpec behavior is uncommon enough that it may not deserve such prominent placement in the API. But if you think it needs to be more discoverable, this is probably where I'd put it. I suppose the value of this new property would be applied only to `MessagePackWriter` instances that it creates itself, since if you are in the more advanced scenario of passing in your own writer instance, you have a chance to configure it yourself. 

Thoughts?

**Comment by AArnott** [comment]
BTW, that's all just from the user point of view. From the perspective of a maintainer of the library, I strongly prefer all MsgPack encoding/decoding to be centralized so it's easier to maintain, audit for spec compliance, etc. Having a resolver writing old spec msgpack binary directly seemed rather bizarre to me when I first encountered it, and reverse engineering how it all worked was a challenge. Now it's very clear to see why the writer and the reader do what they do, and how old spec handling is done.

**Comment by AArnott** [comment]
There is one other angle to this moving oldspec away from resolvers. And it's [a larger issue](#48) that I mean to talk with you about separately.

**Comment by neuecc** [comment]
@AArnott 
It is merged and other work is progressing, but I still do not agree with OldSpec.
But okay, it will talk in the resolver improv section.

> `OldSpec = true`

The addition of such a property is absolutely the opposite.

> This is super-discoverable, and doesn't require that I understand any resolvers at all.

worst.

OldSpec is defined by six years ago.
(this has come from this long issue https://github.com/msgpack/msgpack/issues/121 
 this is the reason for the birth of CBOR)
Obviously, compatibility is not important.
(Of course, compatibility must be possible)

That is, it does not have to be super-discoverable.
It's just like HttpClient(it has HttpClient.Foo and HttpClientHandler.Bar, which setting is there?) or JSON.NET(too many configuration everywhere), Easy and ugly design.

**Pull request merged**
