### PR TITLE
Add immutable collections to Unity

### PR DESCRIPTION
**Pull request by Y-YoL**
Add Immutable for Unity for https://github.com/neuecc/MessagePack-CSharp/pull/1582

### CODE REVIEW

**Comment by AArnott** [comment]
Thanks, but this looks entirely unrelated to my source generator work. Can you send it as its own pull request, targeted at neuecc's repo?

**Comment by Y-YoL** [comment]
I need this to resolve compilation errors in Unity that occur on https://github.com/neuecc/MessagePack-CSharp/pull/1582.  
However, as you said, I can also open this PR as its own pull request.

**Comment by Y-YoL** [comment]
@AArnott  
I found this issue https://github.com/neuecc/MessagePack-CSharp/issues/606.  
Unity is still on .NET Standard 2.1, so things don't seem to have changed since this issue.  
If the policy has not changed since https://github.com/neuecc/MessagePack-CSharp/issues/606, I'm closing this PR and will instead take steps to avoid System.Collections.Immutable references in Unity.

**Comment by AArnott** [comment]
It seems like a reasonable policy change to me. And messagepack has picked up other dependencies on unity. 
I didn't realize my existing PR was causing a build break in unity around immutable collections. How did that happen?

**Pull request closed without merging**
