### PR TITLE
Allow ReadInt* methods to read longer integer types

### LINKED ISSUE #44: ReadInt32 should be willing to read Int64
As requested by @neuecc at https://github.com/AArnott/MessagePack-CSharp/pull/40#issuecomment-468551422

Given some MsgPack writers are in loosely-typed languages where all numbers are 64-bit, and if their MsgPack libraries do not take pains to "compress" the values to shorter integers in the stream, we should adjust our integer readers to allow for reading longer integers, taking care to throw `OverflowException` if the value would be corrupted by the truncation.

### PR DESCRIPTION
**Pull request by AArnott**
* [x] Byte
* [x] SByte
* [x] Int16
* [x] UInt16
* [x] Int32
* [x] UInt32
* [x] Single (will read double, but will never throw OverflowException)

Also add equivalent exhaustive unit testing for:
* [x] Int64
* [x] UInt64

Fixes #44

### CODE REVIEW

**Comment by AArnott** [comment]
@neuecc Is this what you had in mind?

**Comment by neuecc** [comment]
@AArnott Yes.
one more
- [x] Single

**Comment by AArnott** [comment]
I've added Single to the list, but it won't throw OverflowException I think, but will just lose precision when reading a double.

**Comment by AArnott** [comment]
This is ready for final review.

**Pull request merged**
