### PR TITLE
Add MessagePackReader with support for ReadOnlySequence<byte>

### PR DESCRIPTION
**Pull request by AArnott**
This replaces the (byte[]+offset+out bytesRead) reading methods.

These changes are a subset extracted from #27 

Toward overall resolution of #9

### CODE REVIEW

**Comment by AArnott** [comment]
@neuecc I plan to merge this soon so I can follow it up with a `MessagePackWriter` PR. Do you have time to review it in the next 36-48 hours?

**Comment by neuecc** [comment]
@AArnott Okay, this PR is important, I'll check on top priority.

**Comment by neuecc** [comment]
I'm sorry, I misunderstood you.
I thought that PR would come to neuecc/MessagePack-CSharp,
Now is the story to review this PR?

**Comment by neuecc** [comment]
I've started review in 2 areas, performance/api.

Performance:
I've uploaded latest msgpack(1_7_3_4) to PerfBenchmarkDotNet.
At first, run your ReadByte10 vs ReadByte20 test.

```
BenchmarkDotNet=v0.11.4, OS=Windows 10.0.16299.846 (1709/FallCreatorsUpdate/Redstone3)
Intel Core i9-7980XE CPU 2.60GHz, 1 CPU, 36 logical and 18 physical cores
Frequency=2531250 Hz, Resolution=395.0617 ns, Timer=TSC
  [Host] : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3260.0
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3260.0
  Core   : .NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05), 64bit RyuJIT


|     Method |  Job | Runtime | Categories |     Mean |     Error |    StdDev |
|----------- |----- |-------- |----------- |---------:|----------:|----------:|
| ReadByte20 |  Clr |     Clr |        2.0 | 4.829 ns | 0.0920 ns | 0.0984 ns |
| ReadByte20 | Core |    Core |        2.0 | 4.093 ns | 0.0434 ns | 0.0406 ns |
|            |      |         |            |          |           |           |
| ReadByte10 |  Clr |     Clr |        1.0 | 3.273 ns | 0.0222 ns | 0.0197 ns |
| ReadByte10 | Core |    Core |        1.0 | 4.068 ns | 0.0245 ns | 0.0229 ns |
```

New version is slow both Clr and Core?
I'll add more tests and show result tomorrow.

API:
Review and comment tomorrow.

**Comment by AArnott** [comment]
> I thought that PR would come to neuecc/MessagePack-CSharp,

All of the v2.0 changes are still in my fork at the moment.  When you're OK with it, I'll branch off v1.8 in your repo from your current master branch, then start sending PRs from my master to your (new) master to get all my changes into your repo.

> Now is the story to review this PR?

Yes please. I'm taking this large change a piece at a time, and this PR is one of those pieces.

**Comment by AArnott** [comment]
Regarding the perf, on .NET Core the regression is within the margin of error if you consider those columns. I don't think we have anything to worry about there.

On .NET Framework, it's around 1.5ns slower to specifically read a byte. There *might* be something we can optimize there, but unless there's a legit scenario that reads lots of individual bytes, I don't think it'll add up and cause a problem for anyone. These are *nanoseconds* we're talking about here, after all. What do you think?

**Comment by neuecc** [comment]
API:
Should OldSpec compatibility do on Reader?
I thinks it should only care/select in formatter and resolver.
I think, should remove `MessagePackReader.OldSpec` property.

Is ReadBytes returns `ReadOnlySequence<byte>` safe for buffer pool?
Current(1.7.3.4) impl decide it is unsafe so split Readbytes and ReadSegment.
`ExtensionResult.Data` too.

`Skip` is `ReadNextBlock`, so where is `ReadNext` compatibility method?

ReadInt32(and others) can not read Int64 format.

```csharp
byte[] bytes = null;
oldmsgpack::MessagePack.MessagePackBinary.WriteInt64ForceInt64Block(ref bytes, 0, 1);
var reader = new newmsgpack::MessagePack.MessagePackReader(bytes);
Console.WriteLine(reader.ReadInt32()); // exception
```

it is bad, i think this should read and use `checked` cast.

---

Performance:

> I don't think we have anything to worry about there.

Yes, I think too.

But reading small single byte's perfomrance is too bad.

```csharp
[CategoriesColumn]
[Config(typeof(BenchmarkConfig))]
public class SingleMessagePackReaderBenchmark
{
    private byte[] buffer = new byte[1];

    [GlobalSetup]
    public void GlobalSetup()
    {
        this.buffer[0] = newmsgpack::MessagePack.MessagePackCode.MaxFixInt;
    }

    [Benchmark, BenchmarkCategory("2.0")]
    public int SingleReadInt20()
    {
        return new newmsgpack::MessagePack.MessagePackReader(this.buffer).ReadInt32();
    }

    [Benchmark, BenchmarkCategory("1.0")]
    public int SingleReadInt10()
    {
        var offset = 0;
        var result = oldmsgpack::MessagePack.MessagePackBinary.ReadInt32(this.buffer, offset, out int readSize);
        offset += readSize;
        return result;
    }
}
```

```
BenchmarkDotNet=v0.11.4, OS=Windows 10.0.16299.846 (1709/FallCreatorsUpdate/Redstone3)
Intel Core i9-7980XE CPU 2.60GHz, 1 CPU, 36 logical and 18 physical cores
Frequency=2531250 Hz, Resolution=395.0617 ns, Timer=TSC
  [Host] : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3260.0
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3260.0
  Core   : .NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05), 64bit RyuJIT

Platform=X64  IterationCount=1  WarmupCount=1

|          Method |  Job | Runtime | Categories |       Mean | Error | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|---------------- |----- |-------- |----------- |-----------:|------:|------------:|------------:|------------:|--------------------:|
| SingleReadInt20 |  Clr |     Clr |        2.0 | 120.780 ns |    NA |           - |           - |           - |                   - |
| SingleReadInt10 |  Clr |     Clr |        1.0 |   3.028 ns |    NA |           - |           - |           - |                   - |
| SingleReadInt20 | Core |    Core |        2.0 | 102.682 ns |    NA |           - |           - |           - |                   - |
| SingleReadInt10 | Core |    Core |        1.0 |   3.703 ns |    NA |           - |           - |           - |                   - |
```

There are many scenarios to read small bytes.
(read from KVS(Redis, Memcached), read small argument parameter(in RPC), etc...).
If the result of this benchmark is correct, it is critical issue in 2.0.

also check from `Deserialize` path.

```csharp
[CategoriesColumn]
[Config(typeof(BenchmarkConfig))]
public class ReadFromDeserialize
{
    private byte[] buffer = new byte[1];
    newmsgpack::MessagePack.MessagePackSerializer serializer;

    [GlobalSetup]
    public void GlobalSetup()
    {
        this.buffer[0] = newmsgpack::MessagePack.MessagePackCode.MaxFixInt;
        this.serializer = new newmsgpack::MessagePack.MessagePackSerializer();
    }

    [Benchmark, BenchmarkCategory("2.0")]
    public int SingleReadInt20()
    {
        return serializer.Deserialize<int>(buffer);
    }

    [Benchmark, BenchmarkCategory("1.0")]
    public int SingleReadInt10()
    {
        return oldmsgpack::MessagePack.MessagePackSerializer.Deserialize<int>(buffer);
    }
}
```

```
BenchmarkDotNet=v0.11.4, OS=Windows 10.0.16299.846 (1709/FallCreatorsUpdate/Redstone3)
Intel Core i9-7980XE CPU 2.60GHz, 1 CPU, 36 logical and 18 physical cores
Frequency=2531250 Hz, Resolution=395.0617 ns, Timer=TSC
  [Host] : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3260.0
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3260.0
  Core   : .NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05), 64bit RyuJIT

Platform=X64  IterationCount=1  WarmupCount=1

|          Method |  Job | Runtime | Categories |      Mean | Error | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|---------------- |----- |-------- |----------- |----------:|------:|------------:|------------:|------------:|--------------------:|
| SingleReadInt20 |  Clr |     Clr |        2.0 | 154.82 ns |    NA |           - |           - |           - |                   - |
| SingleReadInt10 |  Clr |     Clr |        1.0 |  20.79 ns |    NA |           - |           - |           - |                   - |
| SingleReadInt20 | Core |    Core |        2.0 | 114.61 ns |    NA |           - |           - |           - |                   - |
| SingleReadInt10 | Core |    Core |        1.0 |  17.41 ns |    NA |           - |           - |           - |                   - |
```

**Comment by AArnott** [comment]
Thanks for taking the time to review, @neuecc. I know this is a large PR.

> Should OldSpec compatibility do on Reader?
I thinks it should only care/select in formatter and resolver.
I think, should remove `MessagePackReader.OldSpec` property.

I put it here so we could better consolidate all MessagePack protocol knowledge into the reader/writer themselves. Before, we had some "resolvers" that actually wrote (old spec) MessagePack data directly, which spreads out the knowledge, making it harder to maintain and understand. It's far simpler IMO to have one class responsible for all reading (and just one class for writing, in the next PR) and a visually obvious if check for whether to support old spec or not. 

That said, we might say it's unnecessary to have the OldSpec property on the reader if we simply make the reader able to read both simultaneously. In fact, when OldSpec=true I believe it already handles both cases new and old, so what if we just remove the property, but keep old spec compatibility?

> Is ReadBytes returns `ReadOnlySequence<byte>` safe for buffer pool?
Current(1.7.3.4) impl decide it is unsafe so split Readbytes and ReadSegment.
`ExtensionResult.Data` too.

I'm not sure what you mean about it being safe for buffer pool. Prior to this change, it seems `ReadBytesSegment` didn't copy the buffer while `ReadBytes` did. In the `MessagePackReader`, we never allocate and copy byte buffers around. Instead we perform a constant-time operation which is to return a slice of the original `ReadOnlySequence<byte>`, which involves no allocating and no copying. The caller can then deserialize directly from that, copy it, etc. depending on what they require. As a slice of the original sequence, its lifetime is tied to the original sequence so if the caller wants to preserve it beyond that, it should copy it. 

> `Skip` is `ReadNextBlock`, so where is `ReadNext` compatibility method?

Great question. While at the surface it appeared that `ReadNextBlock` and `ReadNext` were meant to be different, upon close inspection I found them to be equivalent. The `ReadNext` method treats arrays and maps by "skipping over" them using recursive `ReadNext` calls. `ReadNextBlock` simply delegated everything to `ReadNext` except for maps and arrays, which it manually skips over the entire structure via a recursive `ReadNextBlock` call. So the *only* difference is whether maps/arrays are walked over  with `ReadNext` vs. `ReadNextBlock`. That suggests that either `ReadNext` is defective, since it walks less than `ReadNextBlock` but seems to step the same number of times (leaving you in an unknown location in the middle of a complex structure) or it means the two are equivalent. The best I could figure out is that they are in fact equivalent. That's why I just have a `Skip` method and everyone who called either prior method now call `Skip` and all your tests pass. :)

> ReadInt32(and others) can not read Int64 format.
> it is bad, i think this should read and use `checked` cast.

I don't understand the concern here. Both before and after my PR, `ReadInt32` would throw if it encounters an `Int64` formatted integer. Are you suggesting that `ReadInt32` be changed to be willing to read an `Int64` so long as the value is small enough to fit in an `Int32`? That is perhaps fine, but I consider it unrelated to this PR and more of a feature request that could be included separately.

> But reading small single byte's perfomrance is too bad.

I see that you're right, in that the two operations you're comparing are hugely different. But you're not comparing apples to apples here. You're creating a new `MessagePackReader` for every single benchmark on the 2.0 side. Is that really a scenario? Wouldn't people create a reader and then read many times, amortizing the cost across several reads? Even if you called `ReadByte` itself many times, it would quickly amortize the cost. 
What is the scenario where folks have a MessagePack buffer that only contains 1 byte to decode? Why are they even using `MessagePack` if that's always what they deserialize? 
Also, in such a scenario where they are decoding such a small buffer, even if it's 10X slower as your benchmarks show, it's still a small fraction of a millisecond. That seems quite likely to be among the smallest of the costs of whatever they're doing. 
I propose that we keep it this way for 2.0, and if adopters report that they have this scenario and that they actually find it's slowing down their larger scenario significantly, we can bring back a `MessagePackBinary` static class with those read methods that require no initialization at all so they can use it. But I don't want to jump into that now as it adds more code to test and maintain.

**Comment by AArnott** [comment]
Re: performance of creating a `MessagePackReader` and reading just 1 byte:

@neuecc: I have confirmed that 97% of the time in your benchmark is spent initializing the `ReadOnlySequence<byte>` and other structs. That sounds super expensive and we'd have to cut it out completely to have competitive perf if creating a new reader just to read one byte was a scenario. I took a quick look at `SequenceReader` (which `MessagePackReader` uses) and it seems unwise to create all the dual paths that would be necessary to support raw spans as sources. So if we really need to support this, it seems we'd want to look into bringing something like `MessagePackBinary` back.

**Comment by AArnott** [comment]
I removed `MessagePackReader.OldSpec`, and just forced `MessagePackReader` into oldspec compatibility mode permanently. There didn't seem to be any downside to this, and I found a bug in the process which I fixed.

**Comment by neuecc** [comment]
@AArnott 

> New Removed OldSpec MessagePackReader

Wonderful!
But this line is bad, it is only concerned about .NET.
https://github.com/AArnott/MessagePack-CSharp/blob/91efb454b1b5b36cd84d5ac9444617492803a7be/src/MessagePack/MessagePackReader.cs#L783
MessagePackReader should be language-neutral and follow to MsgPack's Spec.
And OldSpec is usually used for intercommunication with older MsgPack serializers in other languages.

> Buffer Pool

I was worried about whether we needed a defensive copy(safety).
It is okay if it is safe.

> read an Int64 so long as the value is small enough to fit in an Int32? 

Yes.
In interoperation with other languages, other serializers do not always return the correct type(PHP, JavaScript, Python, etc...there are not strict about type).
I think that this PR is for approval of MessagePackReader, and I think that it will be merged as it is, unless pointed out here right now.
It is necessary to correct it in the final version.

> Is that really a scenario?

Definitiely yes.
User usualy use `serializer.Deserialize` and it creates MessagePackReader per operate.
https://github.com/AArnott/MessagePack-CSharp/blob/91efb454b1b5b36cd84d5ac9444617492803a7be/src/MessagePack/MessagePackSerializer.cs#L160-L164
So the cost will not be amortizing.
The benchmark figures you made have intentional operations,

> What is the scenario where folks have a MessagePack buffer that only contains 1 byte to decode?

I saied `read from KVS(Redis, Memcached), read small argument parameter(in RPC), etc...)`.

MessagePack is replaced with JSON.
It receives from small data to large data.
It is not always big data.

forexample, RPC( https://github.com/Cysharp/MagicOnion )
`UnaryResult<int> SumAsync(int x, int y)`
is expanded to
```csharp
var x = .Deserialize<int>();
var y = .Deserialize<int>();
var result = SumAsync(x, y);
var sendToClientByte = Serialize<int>(result);
```

KVS ( https://github.com/neuecc/CloudStructures )
```csharp
RedisValue cacheValue = Serialize<(int, string)>((userId, userName));
WriteTo(cacheValue);
(int, string) data = Deserialize<(int, string)>(RedisValue);
```
sometimes call *many* small data in one request so performance is important.
```csharp
var calls = Enumerable.Range(0, 100).Select(x => redis.Get());
await Task.WhenAll(calls); // deserialize 100 small data in one request.
```

for example like the SignalR, game's user position(send/receive per frame(16ms)).
```csharp
Deserialize<Vector3Int>(value); // Vector3Int = (int, int, int)
```

I have an experience of create 5 games in 6 years that used MessagePack(they all are higher traffic than Stackoverflow)
I've created framework that used MessagePack(HTTP/1 WebFramework, HTTP/2 RPC Framework, TCP Realtime Network Engine for game, Redis Library, InMemory Database, etc...)
I've been seeing a lot of "actually using" scenarios.

The data containing 10000 elements which is your example is much less impractical.

It is not good to be poor performance with "realistic" benchmarks.

This PR has been merged, but before releasing performance issues should be solved.
There is a possibility of fundamental change of design, so we should consider now.

**Comment by AArnott** [comment]
Sounds good. Thanks for the scenario. FWIW your SignalR scenario may not be a thing in the future: https://github.com/aspnet/AspNetCore/issues/7387

But I'll see what I can do to optimize the case where the entire message is in a single Span to avoid the ReadOnlySequence.ctor costs. I also wonder though if these deserializers that are calling MessagePack to deserialize a single int aren't themselves already using `ReadOnlySequence<byte>`, in which case they may be able to read a single byte for really cheap since we don't have to create it.

>> read an Int64 so long as the value is small enough to fit in an Int32?

> Yes.
In interoperation with other languages, other serializers do not always return the correct type(PHP, JavaScript, Python, etc...there are not strict about type).
I think that this PR is for approval of MessagePackReader, and I think that it will be merged as it is, unless pointed out here right now.
> It is necessary to correct it in the final version.

Yes, the scenario makes sense. I don't understand why you bring it up now, since this didn't work before my change either, but I have no objection to this enhancement. I'll prepare it soon.

Regarding DateTime, I must have gotten OldSpec confused with another resolver for native .NET DateTime. I'll get that fixed.

**Comment by neuecc** [comment]
About small message of deserialization, there are many cases where only `Nil` is deserialized.

To be exact, `Sum(int x, int y)` is

```csharp
byte[] data; // from gRPC
var (x, y) = Deserialize<(int, int)>(data);
```

Either way, it is still "small data", not be amortizing initialize cost.

**Pull request merged**
